import React,{useEffect,useState} from 'react';
import {Box,Flex,Grid,Heading,Text,Button,HStack,Select,Slider,SliderTrack,SliderFilledTrack,SliderThumb,Switch,Badge,Progress,Divider,useToast} from '@chakra-ui/react';
import {FiSave,FiRotateCcw,FiPlay} from 'react-icons/fi';
import {useAppData} from '../context/AppDataContext';
import {updateAgentConfig} from '../api';

const AgentConfig=()=>{
 const {agents}=useAppData(); const [idx,setIdx]=useState(0),[temp,setTemp]=useState(.7),[topP,setTopP]=useState(.8),[tokens,setTokens]=useState(150),[threshold,setThreshold]=useState(.65),[saving,setSaving]=useState(false),toast=useToast();
 const agent=agents[idx];
 useEffect(()=>{if(agent){setTemp(agent.parameters?.temperature??.7);setTopP(agent.parameters?.top_p??.8);setTokens(agent.parameters?.max_tokens??150);setThreshold(agent.escalationThresholds?.lowConfidence??.65)}},[agent]);
 const save=async()=>{if(!agent)return;setSaving(true);try{await updateAgentConfig(agent.id,{parameters:{temperature:temp,top_p:topP,max_tokens:tokens},escalationThresholds:{lowConfidence:threshold}});toast({title:'Agent configuration saved',status:'success'});}catch(e){toast({title:'Could not save configuration',status:'error'});}finally{setSaving(false)}};
 const reset=()=>{setTemp(agent?.parameters?.temperature??.7);setTopP(agent?.parameters?.top_p??.8);setTokens(agent?.parameters?.max_tokens??150);setThreshold(agent?.escalationThresholds?.lowConfidence??.65)};
 return <Box>
  <Flex justify="space-between" align="center" mb={5}><Box><Text fontSize="11px" color="gray.500" fontWeight="800">AI AGENT CONTROL ROOM</Text><Heading size="lg">{agent?.name||'CSR AI Agent'}</Heading><Text color="gray.500">Tune behavior, guardrails, escalation and capabilities.</Text></Box><HStack><Button size="sm" variant="outline" leftIcon={<FiRotateCcw/>} onClick={reset}>Reset</Button><Button size="sm" leftIcon={<FiSave/>} isLoading={saving} onClick={save}>Save changes</Button></HStack></Flex>
  <Grid templateColumns={{base:'1fr',xl:'1.1fr 1.5fr 1fr'}} gap={4}>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={5}><Flex justify="space-between" mb={5}><Heading size="sm">Behavior configuration</Heading><Select w="160px" value={idx} onChange={e=>setIdx(Number(e.target.value))}>{agents.map((a,i)=><option key={a.id} value={i}>{a.name}</option>)}</Select></Flex>
    {[['Temperature',temp,setTemp,'Creativity'],['Top-p',topP,setTopP,'Response diversity']].map(([n,v,s,d])=><Box mb={6} key={n}><Flex justify="space-between"><Text fontWeight="700" fontSize="12px">{n}</Text><Badge>{v.toFixed(2)}</Badge></Flex><Slider mt={2} value={v} onChange={s} min={0} max={1} step={.01}><SliderTrack><SliderFilledTrack/></SliderTrack><SliderThumb/></Slider><Text fontSize="10px" color="gray.500">{d}</Text></Box>)}<Box mb={6}><Flex justify="space-between"><Text fontWeight="700" fontSize="12px">Max output tokens</Text><Badge>{tokens}</Badge></Flex><Slider mt={2} value={tokens} onChange={setTokens} min={50} max={500} step={10}><SliderTrack><SliderFilledTrack/></SliderTrack><SliderThumb/></Slider></Box><Divider/><Text mt={5} mb={3} fontSize="11px" fontWeight="800">Escalation policy</Text><Flex justify="space-between"><Text fontSize="11px">Minimum confidence</Text><Badge colorScheme="orange">{Math.round(threshold*100)}%</Badge></Flex><Slider mt={2} value={threshold} onChange={setThreshold} min={.2} max={.95} step={.01}><SliderTrack><SliderFilledTrack/></SliderTrack><SliderThumb/></Slider><Text fontSize="10px" color="gray.500">Escalate when confidence falls below this threshold.</Text>
   </Box>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={5}><Heading size="sm">Performance & guardrails</Heading><Text fontSize="10px" color="gray.500" mb={5}>Current operational signals</Text><Grid templateColumns="1fr 1fr" gap={3} mb={5}>{[['Resolution rate','74.6%'],['CSAT','88.0%'],['Escalation rate','11.2%'],['Policy violations','0.7%']].map(([a,b])=><Box key={a} p={3} bg="gray.50" borderRadius="8px"><Text fontSize="10px" color="gray.500">{a}</Text><Text fontWeight="800" fontSize="18px" mt={1}>{b}</Text></Box>)}</Grid>{[['Policy adherence',92,'green'],['Empathy & tone',86,'green'],['Response accuracy',79,'orange'],['Escalation safety',96,'green']].map(([a,v,c])=><Box mb={4} key={a}><Flex justify="space-between" fontSize="10px"><Text>{a}</Text><Text>{v}%</Text></Flex><Progress mt={1} value={v} colorScheme={c} size="xs"/></Box>)}<Heading size="xs" mt={6} mb={3}>Capabilities</Heading>{(agent?.capabilities||[]).map(c=><Flex key={c.id} justify="space-between" py={2} borderBottom="1px solid" borderColor="gray.100"><Text fontSize="11px">{c.name}</Text><Switch size="sm" isChecked={c.enabled} onChange={()=>toast({title:'Capability toggle ready to save',status:'info'})}/></Flex>)}</Box>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={5}><Flex justify="space-between"><Heading size="sm">Simulation console</Heading><Badge colorScheme="green">Simulate</Badge></Flex><Box mt={4} p={3} bg="gray.50" borderRadius="8px"><Text fontSize="10px" color="gray.500">CUSTOMER</Text><Text fontSize="11px" mt={1}>“I was charged twice and need this fixed today.”</Text></Box><Box mt={3} p={3} bg="brand.50" borderRadius="8px"><Text fontSize="10px" color="gray.500">AGENT RESPONSE</Text><Text fontSize="11px" mt={1}>“I can help investigate the duplicate charge and explain the next steps.”</Text></Box><Button mt={3} size="sm" w="100%" leftIcon={<FiPlay/>} onClick={()=>toast({title:'Simulation completed',description:'Policy and escalation checks passed.',status:'success'})}>Run simulation</Button><Divider my={5}/><Heading size="xs" mb={3}>Decision trace</Heading>{['Intent: billing dispute','Policy match: duplicate charge','Confidence: 91%','Escalation: not required'].map(x=><Text key={x} fontSize="10px" py={1.5} borderBottom="1px solid" borderColor="gray.100">{x}</Text>)}<Box mt={4} p={3} bg="green.50" borderRadius="8px"><Text fontSize="11px" fontWeight="800" color="green.700">PASS · 92/100</Text><Text fontSize="10px" color="gray.600">No critical policy violations detected.</Text></Box></Box>
  </Grid>
 </Box>
};
export default AgentConfig;