import React,{useEffect,useMemo,useState} from 'react';
import {Box,Flex,Grid,Heading,Text,Input,Button,Textarea,Select,Badge,VStack,HStack,Divider,Checkbox,useToast} from '@chakra-ui/react';
import {FiPlus,FiStar,FiEdit3,FiX} from 'react-icons/fi';
import {getTemplates,createTemplate,updateTemplate} from '../api';

const fallback=[
{id:'local-1',name:'Welcome new visitor',category:'Onboarding',channel:'Chat',content:'Welcome, {{customer_name}}! How may I help you today?',vars:['customer_name'],favorite:true,isShared:true},
{id:'local-2',name:'Product tour invite',category:'Onboarding',channel:'Email',content:'Hi {{customer_name}}, I’d love to show you around the product.',vars:['customer_name'],favorite:false,isShared:true}
];
const varsFrom=t=>[...new Set([...(t||'').matchAll(/\{\{\s*([a-zA-Z_][\w]*)\s*\}\}/g)].map(m=>m[1]))];

const Templates=()=>{
 const toast=useToast(); const [templates,setTemplates]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[editing,setEditing]=useState(null),[previewValues,setPreviewValues]=useState({});
 useEffect(()=>{getTemplates().then(data=>setTemplates(data.length?data:fallback)).catch(()=>setTemplates(fallback));},[]);
 const filtered=useMemo(()=>templates.filter(t=>(t.name||'').toLowerCase().includes(search.toLowerCase())||(t.category||'').toLowerCase().includes(search.toLowerCase())),[templates,search]);
 const resolved=(selected?.content||'').replace(/\{\{\s*([a-zA-Z_][\w]*)\s*\}\}/g,(_,v)=>previewValues[v]||'['+v+']');
 const save=async()=>{if(!editing?.name||!editing?.content)return; const payload={...editing,variables:undefined}; try{const saved=editing.id&&!String(editing.id).startsWith('local-')?await updateTemplate(editing.id,payload):await createTemplate(payload);setTemplates(prev=>editing.id?prev.map(t=>t.id===editing.id?saved:t):[...prev,saved]);setSelected(saved);setEditing(null);toast({title:'Template saved and shared state updated',status:'success'});}catch(e){const local={...editing,id:editing.id||'local-'+Date.now(),vars:varsFrom(editing.content)};setTemplates(prev=>editing.id?prev.map(t=>t.id===editing.id?local:t):[...prev,local]);setSelected(local);setEditing(null);toast({title:'Template saved locally',status:'warning'});}};
 const openNew=()=>setEditing({name:'',category:'Shipping',channel:'Chat',content:'Hi {{customer_name}}, your request is being reviewed.',isShared:false});
 return <Box>
  <Flex justify="space-between" mb={5} align="center"><Box><Text fontSize="11px" color="gray.500" fontWeight="800">TEMPLATE GOVERNANCE WORKSPACE</Text><Heading size="lg">Response Templates</Heading><Text color="gray.500">Create reusable responses with explicit {{variable}} placeholders.</Text></Box><Button leftIcon={<FiPlus/>} onClick={openNew}>Create template</Button></Flex>
  <Grid templateColumns={{base:'1fr',lg:'180px 1.6fr 310px'}} gap={3}>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={3}><Text fontSize="10px" fontWeight="800" color="gray.400" mb={3}>TEMPLATE LIBRARY</Text>{['All templates','Popular','Low use','Shipping','Returns','Billing','Engagement'].map((x,i)=><Box key={x} py={2} px={2} borderRadius="6px" bg={i===0?'brand.50':'transparent'} color={i===0?'brand.700':'gray.600'} fontSize="11px">{x}</Box>)}<Divider my={4}/><Text fontSize="10px" fontWeight="800" color="gray.400">CHANNELS</Text>{['Chat','Email','Website','Messenger'].map(x=><Text key={x} py={1.5} fontSize="11px">• {x}</Text>)}</Box>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={4}><Flex gap={2} mb={4}><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search templates..."/></Flex><Grid templateColumns={{base:'1fr',md:'1fr 1fr'}} gap={3}>{filtered.map(t=><Box key={t.id} p={4} border="1px solid" borderColor={selected?.id===t.id?'brand.300':'gray.200'} borderRadius="9px" cursor="pointer" onClick={()=>{setSelected(t);setPreviewValues({});}}><Flex justify="space-between"><Badge colorScheme="purple">{t.category}</Badge>{t.favorite&&<FiStar/>}</Flex><Text fontWeight="800" mt={3} fontSize="13px">{t.name}</Text><Text mt={1} fontSize="11px" color="gray.500" noOfLines={2}>{t.content}</Text><Flex mt={3} justify="space-between"><HStack><Badge fontSize="8px">{t.channel||'Chat'}</Badge>{varsFrom(t.content||'').map(v=><Badge key={v} colorScheme="green" fontSize="8px">{'{{'+v+'}}'}</Badge>)}</HStack><Button size="xs" variant="ghost" leftIcon={<FiEdit3/>} onClick={e=>{e.stopPropagation();setEditing({...t})}}>Edit</Button></Flex></Box>)}</Grid></Box>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={4}><Text fontSize="10px" color="gray.400" fontWeight="800">PREVIEW</Text><Heading size="sm" mt={1}>{selected?.name||'Select a template'}</Heading>{varsFrom(selected?.content||'').map(v=><Input key={v} mt={3} size="sm" value={previewValues[v]||''} placeholder={v} onChange={e=>setPreviewValues(p=>({...p,[v]:e.target.value}))}/>) }<Box mt={3} p={4} bg="gray.50" borderRadius="8px" fontSize="12px" lineHeight="1.7">{selected?resolved:'Choose a template to preview.'}</Box>{selected&&<Box mt={4} p={3} bg="green.50" borderRadius="8px"><Text fontSize="10px" fontWeight="800" color="green.700">✓ {varsFrom(selected.content).filter(v=>previewValues[v]).length}/{varsFrom(selected.content).length} variables resolved</Text><Text fontSize="10px" color="gray.600">Placeholders remain visible until values are supplied.</Text></Box>}</Box>
  </Grid>
  {editing&&<Box position="fixed" inset={0} bg="blackAlpha.500" zIndex={50} display="flex" alignItems="center" justifyContent="center" p={4}><Box bg="white" borderRadius="12px" w="min(720px,100%)" p={6} boxShadow="2xl"><Flex justify="space-between" mb={5}><Heading size="md">{editing.id?'Edit Template':'Create Template'}</Heading><Button size="sm" variant="ghost" onClick={()=>setEditing(null)}><FiX/></Button></Flex><Grid templateColumns={{base:'1fr',md:'1fr 1fr'}} gap={4}><Box><Text fontSize="11px" fontWeight="700">Name</Text><Input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><Text fontSize="11px" fontWeight="700" mt={3}>Category</Text><Select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}><option>Shipping</option><option>Returns</option><option>Billing</option><option>Support</option><option>Engagement</option></Select><Text fontSize="11px" fontWeight="700" mt={3}>Channel</Text><Select value={editing.channel} onChange={e=>setEditing({...editing,channel:e.target.value})}><option>Chat</option><option>Email</option><option>Website</option><option>Messenger</option></Select><Checkbox mt={4} isChecked={!!editing.isShared} onChange={e=>setEditing({...editing,isShared:e.target.checked})}>Share with team</Checkbox></Box><Box><Text fontSize="11px" fontWeight="700">Content</Text><Textarea h="180px" value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})} placeholder="Use variables like {{customer_name}} or {{order_id}}"/><Text fontSize="10px" color="gray.500" mt={2}>Detected: {varsFrom(editing.content).map(v=>'{{'+v+'}}').join(', ')||'none'}</Text></Box></Grid><Flex justify="end" gap={2} mt={5}><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button><Button onClick={save}>Save template</Button></Flex></Box></Box>}
 </Box>;
};
export default Templates;