import React,{useMemo,useState} from 'react';
import {Box,Flex,Grid,Heading,Text,Input,Button,Textarea,Select,Badge,VStack,HStack,Divider,useToast} from '@chakra-ui/react';
import {FiSearch,FiPlus,FiStar,FiEdit3,FiX} from 'react-icons/fi';

const initial=[
 {id:1,name:'Welcome new visitor',category:'Onboarding',channel:'Chat',content:'Welcome, {{customer_name}}! How may I help you today?',vars:['customer_name'],favorite:true},
 {id:2,name:'Product tour invite',category:'Onboarding',channel:'Email',content:'Hi {{customer_name}}, I’d love to show you around the product. Would you like a quick tour?',vars:['customer_name'],favorite:false},
 {id:3,name:'Getting started checklist',category:'Support',channel:'Chat',content:'Here is your getting started checklist, {{customer_name}}. Let me know if you need help.',vars:['customer_name'],favorite:false},
 {id:4,name:'Trial follow-up',category:'Sales',channel:'Email',content:'Hi {{customer_name}}, checking in to see how your trial is going.',vars:['customer_name'],favorite:false}
];

const Templates=()=>{
 const [templates,setTemplates]=useState(initial),[search,setSearch]=useState(''),[selected,setSelected]=useState(initial[0]),[editing,setEditing]=useState(null),[preview,setPreview]=useState(''),toast=useToast();
 const filtered=useMemo(()=>templates.filter(t=>t.name.toLowerCase().includes(search.toLowerCase())||t.category.toLowerCase().includes(search.toLowerCase())),[templates,search]);
 const save=()=>{if(!editing.name||!editing.content)return;setTemplates(p=>editing.id?p.map(t=>t.id===editing.id?editing:t):[...p,{...editing,id:Date.now()}]);setSelected(editing);setEditing(null);toast({title:'Template saved',status:'success'});};
 return <Box>
  <Flex justify="space-between" mb={5} align="center"><Box><Text fontSize="11px" color="gray.500" fontWeight="800">TEMPLATE GOVERNANCE WORKSPACE</Text><Heading size="lg">Response Templates</Heading><Text color="gray.500">Create reusable responses and keep variable usage explicit.</Text></Box><Button leftIcon={<FiPlus/>} onClick={()=>setEditing({name:'',category:'Onboarding',channel:'Chat',content:'',vars:['customer_name'],favorite:false})}>Create template</Button></Flex>
  <Grid templateColumns={{base:'1fr',lg:'180px 1.6fr 310px'}} gap={3} minH="650px">
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={3}><Text fontSize="10px" fontWeight="800" color="gray.400" mb={3}>TEMPLATE LIBRARY</Text>{['All templates','Popular','Low use','Onboarding','Billing','Engagement','Transaction'].map((x,i)=><Box key={x} py={2} px={2} borderRadius="6px" bg={i===0?'brand.50':'transparent'} color={i===0?'brand.700':'gray.600'} fontSize="11px" fontWeight={i===0?700:500}>{x}</Box>)}<Divider my={4}/><Text fontSize="10px" fontWeight="800" color="gray.400">CHANNELS</Text>{['Email','Website','Mobile','Messenger'].map(x=><Text key={x} py={1.5} fontSize="11px">• {x}</Text>)}</Box>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={4}><Flex gap={2} mb={4}><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search templates..." /><Select w="140px"><option>All channels</option><option>Chat</option><option>Email</option></Select></Flex><Grid templateColumns={{base:'1fr',md:'1fr 1fr'}} gap={3}>{filtered.map(t=><Box key={t.id} p={4} border="1px solid" borderColor={selected.id===t.id?'brand.300':'gray.200'} borderRadius="9px" cursor="pointer" onClick={()=>{setSelected(t);setPreview(t.content)}} _hover={{borderColor:'brand.300'}}><Flex justify="space-between"><Badge colorScheme="purple" fontSize="9px">{t.category}</Badge>{t.favorite&&<FiStar/>}</Flex><Text fontWeight="800" mt={3} fontSize="13px">{t.name}</Text><Text mt={1} fontSize="11px" color="gray.500" noOfLines={2}>{t.content}</Text><Flex mt={3} justify="space-between"><HStack><Badge fontSize="8px">{t.channel}</Badge>{t.vars.map(v=><Badge key={v} colorScheme="green" fontSize="8px">{'{{'+v+'}}'}</Badge>)}</HStack><Button size="xs" variant="ghost" leftIcon={<FiEdit3/>} onClick={e=>{e.stopPropagation();setEditing(t)}}>Edit</Button></Flex></Box>)}</Grid></Box>
   <Box bg="white" border="1px solid" borderColor="gray.200" borderRadius="10px" p={4}><Text fontSize="10px" color="gray.400" fontWeight="800">PREVIEW</Text><Heading size="sm" mt={1}>{selected?.name}</Heading><Select mt={4} size="sm" value={preview} onChange={e=>setPreview(e.target.value)}><option value={selected?.content}>New visitor</option></Select><Box mt={3} p={4} bg="gray.50" borderRadius="8px" fontSize="12px" lineHeight="1.7">{(preview||selected?.content||'').replace('{{customer_name}}','Alex')}</Box><Box mt={4} p={3} bg="green.50" borderRadius="8px"><Text fontSize="10px" fontWeight="800" color="green.700">✓ 1 variable resolved</Text><Text fontSize="10px" color="gray.600">Variables are shown as {'{{customer_name}}'} in templates and replaced only in preview/send.</Text></Box><Button mt={4} w="100%" onClick={()=>toast({title:'Template ready to insert',status:'success'})}>Use template</Button></Box>
  </Grid>
  {editing&&<Box position="fixed" inset={0} bg="blackAlpha.500" zIndex={50} display="flex" alignItems="center" justifyContent="center" p={4}><Box bg="white" borderRadius="12px" w="min(720px,100%)" p={6} boxShadow="2xl"><Flex justify="space-between" mb={5}><Heading size="md">{editing.id?'Edit Template':'Create Template'}</Heading><Button size="sm" variant="ghost" onClick={()=>setEditing(null)}><FiX/></Button></Flex><Grid templateColumns="1fr 1fr" gap={4}><Box><Text fontSize="11px" fontWeight="700" mb={1}>Name</Text><Input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><Text fontSize="11px" fontWeight="700" mt={3} mb={1}>Category</Text><Select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}><option>Onboarding</option><option>Support</option><option>Billing</option><option>Sales</option></Select><Text fontSize="11px" fontWeight="700" mt={3} mb={1}>Channel</Text><Select value={editing.channel} onChange={e=>setEditing({...editing,channel:e.target.value})}><option>Chat</option><option>Email</option><option>Website</option></Select></Box><Box><Text fontSize="11px" fontWeight="700" mb={1}>Content</Text><Textarea h="180px" value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})} placeholder="Use variables like {{customer_name}}"/><Text fontSize="10px" color="gray.500" mt={2}>Supported variable: <b>{'{{customer_name}}'}</b></Text></Box></Grid><Flex justify="end" gap={2} mt={5}><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button><Button onClick={save}>Save template</Button></Flex></Box></Box>}
 </Box>
};
export default Templates;